package tech.ymservices.tokenizator.model;

public enum TokenType {
	STARS, RANDOMNAME, RANDOMNUMBER, RANDOMADDRESS, RANDOMDATE, RANDOMINTEGER, 
	RANDOMFLOAT, HASH, RANDOMCREDITCARD, RANDOMID, RANDOMIP, RAMDOMINTHELIST 

}
