package tech.ymservices.tokenizator.model;

public enum TokenType {
	STARS, PERSON, RANDOMNUMBER, RANDOMDATE, RANDOMINTEGER, 
	RANDOMFLOAT, HASH, RANDOMCREDITCARD, RANDOMID, IPADDRESS, RAMDOMINTHELIST 

}
